# Generated by Django 4.2.11 on 2024-05-03 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_order_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='discount',
        ),
    ]
